import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "@/components/navigation/Navbar";
import { InstallBootstrap } from "@/components/util/InstallBootstrap";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Weather app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <InstallBootstrap />
          <Navbar />

          <main className="container">{children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
